In [2]:
import pandas as pd
import numpy as np

print("Healthcare Supply Chain & Inventory Analytics")
print("Data Profiling & Validation")

Healthcare Supply Chain & Inventory Analytics
Data Profiling & Validation

In [3]:
demand_sales = pd.read_excel(r"C:\Users\Vasu Bhardwaj\OneDrive\Desktop\Healthcare-Supply-Chain-Inventory-Analytics\data\demand_sales.xlsx")

print("Demand & Sales dataset loaded successfully.")
print("Rows:", demand_sales.shape[0])
print("Columns:", demand_sales.shape[1])

Demand & Sales dataset loaded successfully.
Rows: 14218
Columns: 16

In [4]:
demand_sales.head()

,Order_ID,Order_Date,Patient_ID,Dept,Specialisation,Medicine_ID,DrugName,Formulation,Quantity,ReturnQuantity,Final_Cost,Final_Sales,RtnMRP,Order_Status,Delivery_Date,Lead_Time_Days
0,O00001,2024-06-01,P045,Department1,Specialisation6,M1CA76D1B,ZINC ACETATE 20MG/5ML SYP,Form1,1,0,55.41,59.26,0.0,Cancelled,NaT,0
1,O00002,2024-09-18,P387,Department1,Specialisation7,M318FBCBC,CEFTAZIDIME 2GM+AVIBACTAM 500MG,Form1,1,0,768.64,950.80,0.0,Delivered,2024-09-27,9
2,O00003,2024-11-03,P328,Department3,Specialisation2,M82D7852E,EPTIFIBATIDE 0.75MG/ML,Form2,1,0,774.27,4004.21,0.0,Delivered,2024-11-06,3
3,O00004,2024-01-15,P220,Department1,Specialisation40,MCA6D8773,WATER FOR INJECTION 10ML SOLUTION,Form1,2,0,40.80,81.04,0.0,Cancelled,NaT,0
4,O00005,2024-09-27,P217,Department1,Specialisation5,M18E1DD4A,LORAZEPAM 1MG,Form1,1,0,40.43,40.50,0.0,Delivered,2024-10-09,12

In [5]:
demand_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14218 entries, 0 to 14217
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        14218 non-null  object
 1   Order_Date      14218 non-null  datetime64[ns]
 2   Patient_ID      14218 non-null  object
 3   Dept            14218 non-null  object
 4   Specialisation  14218 non-null  object
 5   Medicine_ID     14218 non-null  object
 6   DrugName        14218 non-null  object
 7   Formulation     14218 non-null  object
 8   Quantity        14218 non-null  int64
 9   ReturnQuantity  14218 non-null  int64
 10  Final_Cost      14218 non-null  float64
 11  Final_Sales     14218 non-null  float64
 12  RtnMRP          14218 non-null  float64
 13  Order_Status    14218 non-null  object
 14  Delivery_Date   13585 non-null  datetime64[ns]
 15  Lead_Time_Days  14218 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(3), object(8)
memory usage: 1.7+ MB

In [6]:
demand_sales.isnull().sum()

Order_ID            0
Order_Date          0
Patient_ID          0
Dept                0
Specialisation      0
Medicine_ID         0
DrugName            0
Formulation         0
Quantity            0
ReturnQuantity      0
Final_Cost          0
Final_Sales         0
RtnMRP              0
Order_Status        0
Delivery_Date     633
Lead_Time_Days      0
dtype: int64

In [7]:
demand_sales.loc[
    demand_sales["Delivery_Date"].isna(),
    "Order_Status"
].value_counts()

Order_Status
Cancelled    633
Name: count, dtype: int64

In [8]:
demand_sales["Order_ID"].duplicated().sum()

np.int64(0)

In [9]:
demand_sales.duplicated().sum()

np.int64(0)

In [10]:
demand_sales["Order_Status"].value_counts()

Order_Status
Delivered    11310
Returned      1681
Cancelled      633
Pending        594
Name: count, dtype: int64

In [11]:
pd.crosstab(
    demand_sales["Order_Status"],
    demand_sales["Delivery_Date"].isna()
)

Delivery_Date  False  True
Order_Status
Cancelled          0    633
Delivered      11310      0
Pending          594      0
Returned        1681      0

In [12]:
demand_sales[[
    "Quantity",
    "ReturnQuantity",
    "Final_Cost",
    "Final_Sales",
    "RtnMRP",
    "Lead_Time_Days"
]].describe()

,Quantity,ReturnQuantity,Final_Cost,Final_Sales,RtnMRP,Lead_Time_Days
count,14218.000000,14218.000000,14218.000000,14218.000000,14218.000000,14218.000000
mean,2.231748,0.291954,124.824039,234.038333,29.126758,8.395344
std,5.132043,1.643322,464.782797,671.261550,182.262341,3.872781
min,0.000000,0.000000,40.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,44.930000,47.815000,0.000000,6.000000
50%,1.000000,0.000000,53.650000,86.420000,0.000000,9.000000
75%,2.000000,0.000000,77.800000,181.000000,0.000000,12.000000
max,150.000000,50.000000,33178.000000,39490.000000,8014.000000,14.000000

In [13]:
demand_sales[
    (demand_sales["Quantity"] == 0) |
    (demand_sales["Final_Sales"] == 0)
][[
    "Order_ID",
    "Order_Status",
    "Quantity",
    "ReturnQuantity",
    "Final_Cost",
    "Final_Sales"
]].head(20)

    Order_ID Order_Status  Quantity  ReturnQuantity  Final_Cost  Final_Sales
5     O00006     Returned         0               8       47.90          0.0
18    O00019     Returned         0               2       70.02          0.0
21    O00022     Returned         0               1       64.86          0.0
32    O00033     Returned         0               1       57.41          0.0
37    O00038     Returned         0               8       70.07          0.0
42    O00043     Returned         0               2       41.37          0.0
68    O00069     Returned         0               1       45.15          0.0
76    O00077     Returned         0               1       46.21          0.0
88    O00089     Returned         0               3      114.59          0.0
89    O00090     Returned         0               2       58.70          0.0
90    O00091     Returned         0               2       51.37          0.0
93    O00094     Returned         0               1       70.91          0.0
101   O00102     Returned         0               1       51.12          0.0
104   O00105     Returned         0               1      118.40          0.0
113   O00114     Returned         0               2       46.27          0.0
116   O00117     Returned         0               1       42.71          0.0
131   O00132     Returned         0               1       64.64          0.0
137   O00138     Returned         0              17       62.27          0.0
144   O00145     Returned         0               2       61.95          0.0
161   O00162     Returned         0               5       43.42          0.0

In [14]:
demand_sales.loc[
    demand_sales["Quantity"] == 0,
    "Order_Status"
].value_counts()

Order_Status
Returned    1681
Name: count, dtype: int64

In [15]:
demand_sales.loc[
    demand_sales["ReturnQuantity"] > 0,
    "Order_Status"
].value_counts()

Order_Status
Returned    1681
Name: count, dtype: int64

In [16]:
(demand_sales["ReturnQuantity"] > demand_sales["Quantity"]).sum()

np.int64(1681)

In [17]:
demand_sales.loc[
    demand_sales["Final_Sales"] == 0,
    "Order_Status"
].value_counts()

Order_Status
Returned    1681
Name: count, dtype: int64

In [19]:
demand_sales.groupby("Order_Status")["Final_Sales"].agg(
    ["count", "sum", "mean"]
).round(2)

              count         sum    mean
Order_Status
Cancelled       633   139838.25  220.91
Delivered     11310  3028992.86  267.82
Pending         594   158725.91  267.22
Returned       1681        0.00    0.00

In [20]:
(demand_sales["Final_Sales"] < demand_sales["Final_Cost"]).sum()

np.int64(1688)

In [21]:
demand_sales.loc[
    demand_sales["Final_Sales"] < demand_sales["Final_Cost"],
    "Order_Status"
].value_counts()

Order_Status
Returned     1681
Delivered       7
Name: count, dtype: int64

In [22]:
demand_sales.loc[
    (demand_sales["Final_Sales"] < demand_sales["Final_Cost"]) &
    (demand_sales["Order_Status"] == "Delivered"),
    [
        "Order_ID",
        "Order_Date",
        "Medicine_ID",
        "DrugName",
        "Quantity",
        "Final_Cost",
        "Final_Sales",
        "RtnMRP",
        "Order_Status"
    ]
]

,Order_ID,Order_Date,Medicine_ID,DrugName,Quantity,Final_Cost,Final_Sales,RtnMRP,Order_Status
654,O00655,2024-05-21,M436D8DEE,POLYETHYLENE GLYCOL 13.125GM + POTASSIUM CHLO...,1,53.75,53.70,0.0,Delivered
1199,O01200,2024-05-07,MF377AD8C,MULTIVITAMIN WITH ZINC AND CURCUMA LONGA EXTR...,1,139.12,134.00,0.0,Delivered
3214,O03215,2024-07-06,M3031DC29,DEXTROSE 10%W/V 500ML IVF,1,46.55,46.31,0.0,Delivered
3405,O03406,2024-08-10,M5998FC4F,DEXTROSE 10%W/V 500ML IVF,1,46.55,46.31,0.0,Delivered
8284,O08285,2024-06-24,MB6370886,GLYCERINE,1,65.03,65.00,0.0,Delivered
8557,O08558,2024-02-03,M880B875A,TAPENTADOL 50MG TAB,1,87.06,86.00,0.0,Delivered
9938,O09939,2024-08-08,M16819ABF,DEXTROSE 10%W/V 500ML IVF,1,46.55,46.31,0.0,Delivered

In [23]:
demand_sales[
    ["Final_Cost", "Final_Sales", "RtnMRP"]
].lt(0).sum()

Final_Cost     0
Final_Sales    0
RtnMRP         0
dtype: int64

In [24]:
demand_sales[
    ["Quantity", "ReturnQuantity"]
].lt(0).sum()

Quantity          0
ReturnQuantity    0
dtype: int64

In [25]:
demand_sales["Order_Date"].agg(["min", "max"])

min   2024-01-01
max   2024-12-27
Name: Order_Date, dtype: datetime64[ns]

In [26]:
demand_sales["Delivery_Date"].agg(["min", "max"])

min   2024-01-02
max   2025-01-10
Name: Delivery_Date, dtype: datetime64[ns]

In [27]:
demand_sales.groupby("Order_Status")["Delivery_Date"].apply(
    lambda x: x.notna().sum()
)

Order_Status
Cancelled        0
Delivered    11310
Pending        594
Returned      1681
Name: Delivery_Date, dtype: int64

In [28]:
(demand_sales["Delivery_Date"] < demand_sales["Order_Date"]).sum()

np.int64(0)

In [29]:
(
    demand_sales["Delivery_Date"] - demand_sales["Order_Date"]
).dt.days.eq(
    demand_sales["Lead_Time_Days"]
).value_counts()

True     13355
False      863
Name: count, dtype: int64

In [30]:
lead_time_mismatch = (
    (demand_sales["Delivery_Date"] - demand_sales["Order_Date"])
    .dt.days
    .ne(demand_sales["Lead_Time_Days"])
)

demand_sales.loc[
    lead_time_mismatch,
    "Order_Status"
].value_counts()

Order_Status
Cancelled    633
Delivered    193
Returned      27
Pending       10
Name: count, dtype: int64

In [31]:
demand_sales.loc[
    lead_time_mismatch &
    (demand_sales["Order_Status"] != "Cancelled"),
    [
        "Order_ID",
        "Order_Date",
        "Delivery_Date",
        "Lead_Time_Days",
        "Order_Status"
    ]
].head(20)

    Order_ID Order_Date Delivery_Date  Lead_Time_Days Order_Status
5     O00006 2024-02-22    2024-03-07              13     Returned
19    O00020 2024-02-21    2024-03-04              11    Delivered
101   O00102 2024-02-25    2024-03-05               8     Returned
132   O00133 2024-02-26    2024-03-03               5    Delivered
148   O00149 2024-02-21    2024-03-02               9    Delivered
169   O00170 2024-02-24    2024-03-01               5    Delivered
201   O00202 2024-02-23    2024-03-05              10    Delivered
233   O00234 2024-02-26    2024-03-12              14    Delivered
263   O00264 2024-02-26    2024-03-05               7    Delivered
273   O00274 2024-02-22    2024-03-02               8     Returned
317   O00318 2024-02-26    2024-03-07               9    Delivered
501   O00502 2024-02-26    2024-03-05               7    Delivered
556   O00557 2024-02-17    2024-03-01              12    Delivered
593   O00594 2024-02-25    2024-03-10              13    Delivered
639   O00640 2024-02-26    2024-03-06               8    Delivered
660   O00661 2024-02-23    2024-03-06              11    Delivered
692   O00693 2024-02-23    2024-03-09              14     Returned
771   O00772 2024-02-24    2024-03-04               8    Delivered
775   O00776 2024-02-23    2024-03-06              11    Delivered
779   O00780 2024-02-27    2024-03-02               3     Returned

In [32]:
actual_lead_time = (
    demand_sales["Delivery_Date"] - demand_sales["Order_Date"]
).dt.days

lead_time_difference = (
    actual_lead_time - demand_sales["Lead_Time_Days"]
)

lead_time_difference[
    lead_time_mismatch &
    (demand_sales["Order_Status"] != "Cancelled")
].value_counts().sort_index()

1.0    230
Name: count, dtype: int64

In [33]:
demand_sales["Calculated_Lead_Time_Days"] = (
    demand_sales["Delivery_Date"] - demand_sales["Order_Date"]
).dt.days

In [34]:
demand_sales["Order_Status"].value_counts()

Order_Status
Delivered    11310
Returned      1681
Cancelled      633
Pending        594
Name: count, dtype: int64

In [35]:
demand_sales["Dept"].value_counts()

Dept
Department1    12440
Department2     1566
Department3      212
Name: count, dtype: int64

In [36]:
demand_sales["Specialisation"].value_counts()

Specialisation
Specialisation4     3999
Specialisation7     2098
Specialisation3      734
Specialisation2      609
Specialisation8      594
Specialisation20     554
Specialisation11     516
Specialisation16     509
Specialisation1      440
Specialisation14     436
Specialisation5      390
Specialisation21     360
Specialisation26     342
Specialisation6      251
Specialisation23     249
Specialisation25     201
Specialisation31     184
Specialisation17     178
Specialisation9      158
Specialisation15     143
Specialisation42     132
Specialisation27     117
Specialisation10     107
Specialisation50     100
Specialisation33      99
Specialisation55      91
Specialisation43      74
Specialisation45      55
Specialisation34      53
Specialisation39      47
Specialisation41      44
Specialisation40      43
Specialisation28      34
Specialisation19      30
Specialisation48      24
Specialisation49      23
Specialisation12      23
Specialisation61      23
Specialisation54      20
Specialisation44      17
Specialisation22      16
Specialisation65      15
Specialisation57      14
Specialisation38      14
Specialisation24      10
Specialisation63       8
Specialisation53       7
Specialisation75       6
Specialisation70       6
Specialisation13       5
Specialisation18       5
Specialisation51       3
Specialisation60       2
Specialisation37       2
Specialisation35       1
Specialisation67       1
Specialisation52       1
Specialisation59       1
Name: count, dtype: int64

In [37]:
demand_sales["Formulation"].value_counts()

Formulation
Form1     11622
Form2      1325
            653
Patent      539
Form3        79
Name: count, dtype: int64

In [38]:
demand_sales["Formulation"].isna().sum()

np.int64(0)

In [39]:
demand_sales.loc[
    demand_sales["Formulation"].astype(str).str.strip() == "",
    "Formulation"
].value_counts(dropna=False)

Formulation
    653
Name: count, dtype: int64

In [40]:
demand_sales.loc[
    demand_sales["Formulation"].astype(str).str.strip() == "",
    ["Medicine_ID", "DrugName", "Formulation"]
].head(20)

    Medicine_ID                           DrugName Formulation
21    M5011CBB7    MULTIPLE ELECTROLYTES 500ML IVF
29    M0C7BA64A           POTASSIUM CHLORIDE 150MG
32    MA129C24E   CALCIUM 250MG + VITAMIN D3 125IU
76    MFDD7C6AA          DEXTROSE 10%W/V 500ML IVF
88    M290977A8    MULTIPLE ELECTROLYTES 500ML IVF
89    MBCEC8739
93    MC58552F2              DOXYCYCLINE 100MG INJ
101   M6F0EA4CD               SODIUM CHLORIDE 0.9%
113   M7B6251C2           POTASSIUM CHLORIDE 150MG
137   MDC0677E2
166   MA57B6C8F                           TRAMADOL
178   M4DAE4C72                           TRAMADOL
179   M28516A5F               TIGECYCLINE 50MG INJ
221   M135656C2
230   M61DDB968
243   M612E05E9
258   M98BE563A    MULTIPLE ELECTROLYTES 500ML IVF
260   MD15A2ABA    MULTIPLE ELECTROLYTES 500ML IVF
276   M32BC9116               SODIUM CHLORIDE 0.9%
291   M021D4D88         LEVETIRACETAM 100MG/ML INJ

In [41]:
blank_formulation = demand_sales["Formulation"].astype(str).str.strip() == ""

demand_sales.loc[
    blank_formulation,
    "Medicine_ID"
].isin(
    demand_sales.loc[~blank_formulation, "Medicine_ID"]
).sum()

np.int64(0)

In [42]:
demand_sales["Medicine_ID"].nunique()

14218

In [43]:
numeric_cols = [
    "Quantity",
    "ReturnQuantity",
    "Final_Cost",
    "Final_Sales",
    "RtnMRP",
    "Lead_Time_Days"
]

demand_sales[numeric_cols].lt(0).sum()

Quantity          0
ReturnQuantity    0
Final_Cost        0
Final_Sales       0
RtnMRP            0
Lead_Time_Days    0
dtype: int64

In [44]:
consumption_facility = pd.read_excel(r"C:\Users\Vasu Bhardwaj\OneDrive\Desktop\Healthcare-Supply-Chain-Inventory-Analytics\data\consumption_facility.xlsx" )

print("Consumption Facility dataset loaded successfully.")
print("Rows:", consumption_facility.shape[0])
print("Columns:", consumption_facility.shape[1])

Consumption Facility dataset loaded successfully.
Rows: 11111
Columns: 9

In [45]:
print("=== INFO ===")
consumption_facility.info()

print("\n=== MISSING VALUES ===")
print(consumption_facility.isna().sum())

print("\n=== DUPLICATE ROWS ===")
print(consumption_facility.duplicated().sum())

=== INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11111 entries, 0 to 11110
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               11111 non-null  object
 1   Region                   11111 non-null  object
 2   Medicine_ID              11111 non-null  object
 3   DrugName                 11111 non-null  object
 4   Daily_Consumption_Units  11111 non-null  float64
 5   Out_of_Stock_Days        11111 non-null  int64
 6   Wastage_Units            11111 non-null  int64
 7   Bed_Days                 11111 non-null  int64
 8   Supplies_Used            11111 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 781.4+ KB

=== MISSING VALUES ===
Patient_ID                 0
Region                     0
Medicine_ID                0
DrugName                   0
Daily_Consumption_Units    0
Out_of_Stock_Days          0
Wastage_Units              0
Bed_Days                   0
Supplies_Used              0
dtype: int64

=== DUPLICATE ROWS ===
0

In [46]:
numeric_cols_cf = [
    "Daily_Consumption_Units",
    "Out_of_Stock_Days",
    "Wastage_Units",
    "Bed_Days"
]

consumption_facility[numeric_cols_cf].lt(0).sum()

Daily_Consumption_Units    0
Out_of_Stock_Days          0
Wastage_Units              0
Bed_Days                   0
dtype: int64

In [47]:
print("=== REGION ===")
print(consumption_facility["Region"].value_counts())

print("\n=== SUPPLIES USED ===")
print(consumption_facility["Supplies_Used"].value_counts())

=== REGION ===
Region
Mumbai         1394
Hyderabad       933
Chennai         854
Lucknow         728
Ahmedabad       699
Pune            699
Kolkata         685
Delhi           683
Bangalore       664
Indore          662
Nagpur          623
Jaipur          554
Guwahati        426
Coimbatore      423
Surat           275
Patna           230
Bhubaneswar     227
Kanpur          178
Raipur          174
Name: count, dtype: int64

=== SUPPLIES USED ===
Supplies_Used
Mask, Gown    3731
Gloves, IV    3711
Gown, IV      3669
Name: count, dtype: int64

In [48]:
inventory_stock = pd.read_excel(
    r"C:\Users\Vasu Bhardwaj\OneDrive\Desktop\Healthcare-Supply-Chain-Inventory-Analytics\data\inventory_stock.xlsx"
)

print("Inventory Stock dataset loaded successfully.")
print("Rows:", inventory_stock.shape[0])
print("Columns:", inventory_stock.shape[1])

Inventory Stock dataset loaded successfully.
Rows: 841
Columns: 16

In [49]:
print("=== INFO ===")
inventory_stock.info()

print("\n=== MISSING VALUES ===")
print(inventory_stock.isna().sum())

print("\n=== DUPLICATE ROWS ===")
print(inventory_stock.duplicated().sum())

=== INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 841 entries, 0 to 840
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Medicine_ID             841 non-null    object
 1   DrugName                841 non-null    object
 2   Formulation             841 non-null    object
 3   Category                841 non-null    object
 4   Batch_No                841 non-null    object
 5   Manufacture_Date        841 non-null    datetime64[ns]
 6   Expiry_Date             841 non-null    datetime64[ns]
 7   Current_Stock           841 non-null    int64
 8   Min_Required            841 non-null    int64
 9   Max_Capacity            841 non-null    int64
 10  Unit_Cost               841 non-null    float64
 11  Avg_Usage_Per_Day       841 non-null    int64
 12  Restock_Lead_Time_Days  841 non-null    int64
 13  Reorder_Level           841 non-null    int64
 14  Stock_Cover_Days        841 non-null    int64
 15  Vendor_ID               841 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(7), object(6)
memory usage: 105.3+ KB

=== MISSING VALUES ===
Medicine_ID               0
DrugName                  0
Formulation               0
Category                  0
Batch_No                  0
Manufacture_Date          0
Expiry_Date               0
Current_Stock             0
Min_Required              0
Max_Capacity              0
Unit_Cost                 0
Avg_Usage_Per_Day         0
Restock_Lead_Time_Days    0
Reorder_Level             0
Stock_Cover_Days          0
Vendor_ID                 0
dtype: int64

=== DUPLICATE ROWS ===
0

In [50]:
inventory_numeric_cols = [
    "Current_Stock",
    "Min_Required",
    "Max_Capacity",
    "Unit_Cost",
    "Avg_Usage_Per_Day",
    "Restock_Lead_Time_Days",
    "Reorder_Level",
    "Stock_Cover_Days"
]

inventory_stock[inventory_numeric_cols].lt(0).sum()

Current_Stock             0
Min_Required              0
Max_Capacity              0
Unit_Cost                 0
Avg_Usage_Per_Day         0
Restock_Lead_Time_Days    0
Reorder_Level             0
Stock_Cover_Days          0
dtype: int64

In [51]:
print("Current Stock > Max Capacity:",
      (inventory_stock["Current_Stock"] > inventory_stock["Max_Capacity"]).sum())

print("Min Required > Max Capacity:",
      (inventory_stock["Min_Required"] > inventory_stock["Max_Capacity"]).sum())

print("Reorder Level > Max Capacity:",
      (inventory_stock["Reorder_Level"] > inventory_stock["Max_Capacity"]).sum())

Current Stock > Max Capacity: 0
Min Required > Max Capacity: 0
Reorder Level > Max Capacity: 0

In [52]:
print("Expiry before Manufacture:",
      (inventory_stock["Expiry_Date"] < inventory_stock["Manufacture_Date"]).sum())

Expiry before Manufacture: 0

In [53]:
supplier_procurement = pd.read_excel(
    r"C:\Users\Vasu Bhardwaj\OneDrive\Desktop\Healthcare-Supply-Chain-Inventory-Analytics\data\supplier_procurement.xlsx"
)

print("Supplier Procurement dataset loaded successfully.")
print("Rows:", supplier_procurement.shape[0])
print("Columns:", supplier_procurement.shape[1])

Supplier Procurement dataset loaded successfully.
Rows: 538
Columns: 9

In [54]:
print("=== INFO ===")
supplier_procurement.info()

print("\n=== MISSING VALUES ===")
print(supplier_procurement.isna().sum())

print("\n=== DUPLICATE ROWS ===")
print(supplier_procurement.duplicated().sum())

=== INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 538 entries, 0 to 537
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Supplier_ID            538 non-null    object
 1   Supplier_Name          538 non-null    object
 2   Region                 538 non-null    object
 3   Avg_Lead_Time_Days     538 non-null    int64
 4   Reliability_Score      538 non-null    float64
 5   Cost_Per_Item          538 non-null    float64
 6   Last_Order_Date        538 non-null    datetime64[ns]
 7   Next_Delivery_Date     538 non-null    datetime64[ns]
 8   On_Time_Delivery_Rate  538 non-null    int64
dtypes: datetime64[ns](2), float64(2), int64(2), object(3)
memory usage: 38.0+ KB

=== MISSING VALUES ===
Supplier_ID              0
Supplier_Name            0
Region                   0
Avg_Lead_Time_Days       0
Reliability_Score        0
Cost_Per_Item            0
Last_Order_Date          0
Next_Delivery_Date       0
On_Time_Delivery_Rate    0
dtype: int64

=== DUPLICATE ROWS ===
0

In [55]:
print("Negative Avg Lead Time:",
      (supplier_procurement["Avg_Lead_Time_Days"] < 0).sum())

print("Negative Cost Per Item:",
      (supplier_procurement["Cost_Per_Item"] < 0).sum())

print("Invalid Delivery Date:",
      (supplier_procurement["Next_Delivery_Date"] < supplier_procurement["Last_Order_Date"]).sum())

Negative Avg Lead Time: 0
Negative Cost Per Item: 0
Invalid Delivery Date: 0

In [56]:
print("Reliability Score outside 0-1:",
      ((supplier_procurement["Reliability_Score"] < 0) |
       (supplier_procurement["Reliability_Score"] > 1)).sum())

print("On-Time Delivery Rate outside 0-100:",
      ((supplier_procurement["On_Time_Delivery_Rate"] < 0) |
       (supplier_procurement["On_Time_Delivery_Rate"] > 100)).sum())

Reliability Score outside 0-1: 538
On-Time Delivery Rate outside 0-100: 0

In [57]:
supplier_procurement["Reliability_Score"].describe()

count    538.000000
mean       4.292751
std        0.432225
min        3.500000
25%        3.900000
50%        4.300000
75%        4.700000
max        5.000000
Name: Reliability_Score, dtype: float64

In [58]:
print("Reliability Score outside 1-5:",
      ((supplier_procurement["Reliability_Score"] < 1) |
       (supplier_procurement["Reliability_Score"] > 5)).sum())

Reliability Score outside 1-5: 0

In [59]:
import os

cleaned_path = os.path.join("..", "data", "cleaned")

os.makedirs(cleaned_path, exist_ok=True)

print("Cleaned data folder ready:", cleaned_path)

Cleaned data folder ready: ..\data\cleaned